/**
 * Shared browser-side extraction script for interactable elements.
 *
 * This script is evaluated inside the target page via browser.evaluate() by
 * BOTH recon paths:
 *   - initial application recon (orchestrator/runner.ts runRecon)
 *   - post-action recon snapshots (orchestrator/runner.ts post-action hook)
 *
 * Keeping it in one place guarantees initial and fresh recon produce the same
 * trusted ApplicationRecon.interactableElements structure — a selector
 * discovered after a state-changing action is validated exactly like one
 * discovered during initial recon.
 *
 * Contract: the script string contains "getSelector"; tests route mocks on
 * that marker. Elements are emitted with CSS selectors generated by priority
 * (id > href > name > type > data-testid > data-cy > aria-label >
 * role+aria-label > structural path). The structural path computes each
 * segment's :nth-of-type from THAT segment's own same-tag sibling position.
 */
export const INTERACTABLE_EXTRACTION_SCRIPT = `
        (() => {
          const results = [];

          // Helper: build a unique CSS selector for an element
          function getSelector(el) {
            if (el.id) return '#' + CSS.escape(el.id);
            const tag = el.tagName.toLowerCase();

            // Try href-based selector for links (most specific for links)
            if (tag === 'a' && el.getAttribute('href')) {
              const href = el.getAttribute('href');
              if (href && (href.startsWith('#') || href.startsWith('/'))) {
                return 'a[href="' + CSS.escape(href) + '"]';
              }
              if (href && !href.startsWith('javascript:')) {
                return 'a[href="' + CSS.escape(href) + '"]';
              }
            }

            // Try name attribute for form inputs (unique per form)
            if (['input','select','textarea'].includes(tag) && el.name) {
              // Check if name is unique in the document
              const nameCount = document.querySelectorAll(tag + '[name="' + CSS.escape(el.name) + '"]').length;
              if (nameCount === 1) return tag + '[name="' + CSS.escape(el.name) + '"]';
              // Not unique — prefix with parent form id or class
              const form = el.closest('form');
              if (form && form.id) return '#' + CSS.escape(form.id) + ' ' + tag + '[name="' + CSS.escape(el.name) + '"]';
              return tag + '[name="' + CSS.escape(el.name) + '"]';
            }

            // Try type for submit buttons
            if (tag === 'input' && el.type) {
              return 'input[type="' + CSS.escape(el.type) + '"]';
            }

            // Try data-testid or data-cy (test IDs are designed to be unique)
            if (el.getAttribute('data-testid')) return '[data-testid="' + CSS.escape(el.getAttribute('data-testid')) + '"]';
            if (el.getAttribute('data-cy')) return '[data-cy="' + CSS.escape(el.getAttribute('data-cy')) + '"]';

            // Try aria-label (often unique)
            if (el.getAttribute('aria-label')) {
              const label = el.getAttribute('aria-label');
              const labelCount = document.querySelectorAll('[aria-label="' + CSS.escape(label) + '"]').length;
              if (labelCount === 1) return '[aria-label="' + CSS.escape(label) + '"]';
            }

            // Try role + accessible name (Playwright-compatible)
            const role = el.getAttribute('role');
            if (role) {
              const accessibleName = el.textContent?.trim().slice(0, 50) || '';
              if (accessibleName) return '[role="' + role + '"][aria-label="' + CSS.escape(accessibleName) + '"]';
            }

            // Build a path from the element up to a unique ancestor.
            // Each segment's :nth-of-type must describe THAT segment's own
            // position among its same-tag siblings. The previous version
            // computed the index for the advancing ancestor but appended it
            // to the immutable tail, producing selectors like
            // div > p > button:nth-of-type(2) that match 0 elements.
            function nthSegment(elm) {
              const segTag = elm.tagName.toLowerCase();
              const segParent = elm.parentElement;
              if (!segParent || segParent === document.body) return segTag;
              const sameTag = Array.from(segParent.children).filter(c => c.tagName === elm.tagName);
              if (sameTag.length <= 1) return segTag;
              return segTag + ':nth-of-type(' + (sameTag.indexOf(elm) + 1) + ')';
            }
            let current = el;
            let path = nthSegment(el);
            while (current.parentElement && current.parentElement !== document.body) {
              const parent = current.parentElement;

              if (parent.id) {
                return '#' + CSS.escape(parent.id) + ' > ' + path;
              }

              path = nthSegment(parent) + ' > ' + path;

              current = parent;

              // Stop if path is already specific enough
              if (path.split(' > ').length >= 3) break;
            }

            return path;
          }

          function getInfo(el) {
            const text = (el.textContent || '').trim().replace(/\\s+/g, ' ').slice(0, 80);
            const classes = Array.from(el.classList || []).slice(0, 3);
            const info = {
              selector: getSelector(el),
              text,
              tag: el.tagName.toLowerCase(),
            };
            if (el.href) info.href = el.getAttribute('href');
            if (el.name) info.name = el.name;
            if (el.type) info.type = el.type;
            if (el.placeholder) info.placeholder = el.placeholder;
            if (el.id) info.id = el.id;
            if (el.getAttribute('role')) info.role = el.getAttribute('role');
            if (el.getAttribute('aria-label')) info.ariaLabel = el.getAttribute('aria-label');
            if (classes.length > 0) info.classes = classes;
            return info;
          }

          // Navigation links
          document.querySelectorAll('nav a, [role="navigation"] a').forEach(a => {
            results.push(getInfo(a));
          });

          // All visible links with href
          document.querySelectorAll('a[href]').forEach(a => {
            const text = (a.textContent || '').trim();
            if (text && text.length > 0 && text.length < 80) {
              const sel = getSelector(a);
              if (!results.some(r => r.selector === sel)) {
                results.push(getInfo(a));
              }
            }
          });

          // Buttons
          document.querySelectorAll('button, [role="button"], input[type="submit"]').forEach(b => {
            results.push(getInfo(b));
          });

          // Form inputs
          document.querySelectorAll('form input, form select, form textarea, input[name], textarea[name]').forEach(inp => {
            results.push(getInfo(inp));
          });

          // Sections with IDs (anchor targets)
          document.querySelectorAll('[id]').forEach(el => {
            if (el.tagName !== 'HTML' && el.tagName !== 'BODY' && el.id) {
              results.push({
                selector: '#' + CSS.escape(el.id),
                text: (el.textContent || '').trim().slice(0, 40),
                tag: el.tagName.toLowerCase(),
                id: el.id,
              });
            }
          });

          return results.slice(0, 50);
        })()
      `;
